/**
 * HelpOS Docs.js — AI-powered document summarization and study questions.
 */
document.addEventListener('DOMContentLoaded', () => {
  const docInput = document.getElementById('doc-input');
  const docOutput = document.getElementById('doc-output');
  const summaryBtn = document.getElementById('doc-summary-btn');
  const questionsBtn = document.getElementById('doc-questions-btn');

  if (!docInput || !docOutput || !summaryBtn || !questionsBtn) return;

  function showDocError(message) {
    docOutput.className = 'result-card markdown-output';
    docOutput.innerHTML = `<p class="docs-error">⚠ ${escapeHtml(message)}</p>`;
  }

  function showDocLoading(label) {
    docOutput.className = 'result-card markdown-output docs-loading';
    docOutput.innerHTML = `<div class="docs-status">${escapeHtml(label)}</div>`;
  }

  function showDocResult(content) {
    docOutput.className = 'result-card markdown-output';
    docOutput.innerHTML = `
      <div class="docs-status docs-status-success">Generated by local AI</div>
      <div class="docs-result-body">${renderMarkdown(content)}</div>`;
    wireCopyCodeButtons(docOutput);
  }

  async function runDocAction(action) {
    const text = docInput.value.trim();
    if (!text) {
      docOutput.className = 'result-card empty-state';
      docOutput.textContent = 'Paste document text first.';
      return;
    }

    const activeBtn = action === 'summary' ? summaryBtn : questionsBtn;
    const otherBtn = action === 'summary' ? questionsBtn : summaryBtn;
    const idleLabel = action === 'summary' ? 'Summarize' : 'Make study questions';
    const busyLabel = action === 'summary' ? 'Summarizing…' : 'Generating…';

    activeBtn.disabled = true;
    otherBtn.disabled = true;
    activeBtn.textContent = busyLabel;
    showDocLoading('Working with local AI…');

    try {
      const res = await fetch('/api/docs', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action, text }),
      });

      let data;
      try {
        data = await res.json();
      } catch {
        showDocError('Server returned an invalid response. Hard-refresh the page (Cmd+Shift+R) and try again.');
        return;
      }

      if (!res.ok) {
        showDocError(data.detail || `Request failed (${res.status}).`);
        return;
      }

      if (data.source !== 'helpos-docs' || data.mode !== 'reasoning' || !data.content) {
        showDocError('Unexpected response from Docs API. Hard-refresh the page (Cmd+Shift+R) and try again.');
        return;
      }

      showDocResult(data.content);
    } catch (err) {
      showDocError(`Network error: ${err.message}`);
    } finally {
      activeBtn.disabled = false;
      otherBtn.disabled = false;
      activeBtn.textContent = idleLabel;
    }
  }

  summaryBtn.addEventListener('click', () => runDocAction('summary'));
  questionsBtn.addEventListener('click', () => runDocAction('questions'));
});
